"""initial schema

Revision ID: 144a7596dce2
Revises: 
Create Date: 2026-04-20 18:34:54.734824

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '144a7596dce2'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('student', 'professor', name='user_role'), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('subjects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('professor_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['professor_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('professor_id', 'name', name='uq_subjects_professor_name')
    )
    op.create_index(op.f('ix_subjects_id'), 'subjects', ['id'], unique=False)
    op.create_index(op.f('ix_subjects_professor_id'), 'subjects', ['professor_id'], unique=False)
    op.create_table('gmail_accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_email', sa.String(length=255), nullable=False),
    sa.Column('credentials_json', sa.Text(), nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=True),
    sa.Column('professor_id', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['professor_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('professor_id', 'account_email', name='uq_gmail_accounts_professor_email')
    )
    op.create_index(op.f('ix_gmail_accounts_account_email'), 'gmail_accounts', ['account_email'], unique=False)
    op.create_index(op.f('ix_gmail_accounts_id'), 'gmail_accounts', ['id'], unique=False)
    op.create_index(op.f('ix_gmail_accounts_professor_id'), 'gmail_accounts', ['professor_id'], unique=False)
    op.create_index(op.f('ix_gmail_accounts_subject_id'), 'gmail_accounts', ['subject_id'], unique=False)
    op.create_table('projects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('topic', sa.String(length=255), nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('subject_id', 'name', name='uq_projects_subject_name')
    )
    op.create_index(op.f('ix_projects_id'), 'projects', ['id'], unique=False)
    op.create_index(op.f('ix_projects_subject_id'), 'projects', ['subject_id'], unique=False)
    op.create_table('enrollments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('active', 'completed', 'overdue', 'dropped', name='enrollment_status'), server_default='active', nullable=False),
    sa.Column('current_deliverable', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.Column('enrolled_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('current_deliverable >= 1 AND current_deliverable <= 4', name='ck_enrollments_current_deliverable_range'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('student_id', 'project_id', name='uq_enrollments_student_project')
    )
    op.create_index(op.f('ix_enrollments_id'), 'enrollments', ['id'], unique=False)
    op.create_index(op.f('ix_enrollments_project_id'), 'enrollments', ['project_id'], unique=False)
    op.create_index(op.f('ix_enrollments_student_id'), 'enrollments', ['student_id'], unique=False)
    op.create_table('submissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('enrollment_id', sa.Integer(), nullable=False),
    sa.Column('deliverable_number', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('submitted', 'evaluated', 'overdue', name='submission_status'), server_default='submitted', nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deadline_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('deliverable_number >= 1 AND deliverable_number <= 4', name='ck_submissions_deliverable_number_range'),
    sa.ForeignKeyConstraint(['enrollment_id'], ['enrollments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('enrollment_id', 'deliverable_number', name='uq_submissions_enrollment_deliverable')
    )
    op.create_index(op.f('ix_submissions_enrollment_id'), 'submissions', ['enrollment_id'], unique=False)
    op.create_index(op.f('ix_submissions_id'), 'submissions', ['id'], unique=False)
    op.create_table('evaluations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('submission_id', sa.Integer(), nullable=False),
    sa.Column('ai_score', sa.Integer(), nullable=False),
    sa.Column('criteria_breakdown', sa.JSON(), nullable=False),
    sa.Column('feedback', sa.Text(), nullable=False),
    sa.Column('evaluated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_overridden', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('override_score', sa.Integer(), nullable=True),
    sa.Column('override_comment', sa.Text(), nullable=True),
    sa.Column('override_by_professor_id', sa.Integer(), nullable=True),
    sa.Column('override_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('(override_score IS NULL) OR (override_score >= 0 AND override_score <= 100)', name='ck_evaluations_override_score_range'),
    sa.CheckConstraint('ai_score >= 0 AND ai_score <= 100', name='ck_evaluations_ai_score_range'),
    sa.ForeignKeyConstraint(['override_by_professor_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['submission_id'], ['submissions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('submission_id', name='uq_evaluations_submission')
    )
    op.create_index(op.f('ix_evaluations_id'), 'evaluations', ['id'], unique=False)
    op.create_index(op.f('ix_evaluations_submission_id'), 'evaluations', ['submission_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_evaluations_submission_id'), table_name='evaluations')
    op.drop_index(op.f('ix_evaluations_id'), table_name='evaluations')
    op.drop_table('evaluations')
    op.drop_index(op.f('ix_submissions_id'), table_name='submissions')
    op.drop_index(op.f('ix_submissions_enrollment_id'), table_name='submissions')
    op.drop_table('submissions')
    op.drop_index(op.f('ix_enrollments_student_id'), table_name='enrollments')
    op.drop_index(op.f('ix_enrollments_project_id'), table_name='enrollments')
    op.drop_index(op.f('ix_enrollments_id'), table_name='enrollments')
    op.drop_table('enrollments')
    op.drop_index(op.f('ix_projects_subject_id'), table_name='projects')
    op.drop_index(op.f('ix_projects_id'), table_name='projects')
    op.drop_table('projects')
    op.drop_index(op.f('ix_gmail_accounts_subject_id'), table_name='gmail_accounts')
    op.drop_index(op.f('ix_gmail_accounts_professor_id'), table_name='gmail_accounts')
    op.drop_index(op.f('ix_gmail_accounts_id'), table_name='gmail_accounts')
    op.drop_index(op.f('ix_gmail_accounts_account_email'), table_name='gmail_accounts')
    op.drop_table('gmail_accounts')
    op.drop_index(op.f('ix_subjects_professor_id'), table_name='subjects')
    op.drop_index(op.f('ix_subjects_id'), table_name='subjects')
    op.drop_table('subjects')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
