"""add project gmail account and submission email status

Revision ID: 14dcb62dd069
Revises: 144a7596dce2
Create Date: 2026-04-24 02:09:29.716691

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '14dcb62dd069'
down_revision: Union[str, Sequence[str], None] = '144a7596dce2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('gmail_account_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_projects_gmail_account_id'), 'projects', ['gmail_account_id'], unique=False)
    op.create_foreign_key(None, 'projects', 'gmail_accounts', ['gmail_account_id'], ['id'], ondelete='SET NULL')
    op.add_column('submissions', sa.Column('email_sent', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('submissions', sa.Column('email_error', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('submissions', 'email_error')
    op.drop_column('submissions', 'email_sent')
    op.drop_constraint(None, 'projects', type_='foreignkey')
    op.drop_index(op.f('ix_projects_gmail_account_id'), table_name='projects')
    op.drop_column('projects', 'gmail_account_id')
    # ### end Alembic commands ###
